spring:
  application:
    name: front
  profiles:
    active: prod

  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://localhost:10355
      profile: ${spring.profiles.active}
      label: main
      fail-fast: true
