app:
  api:
    prefix: http://localhost:8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

server:
  port: 8082

# front는 eureka 미사용, gateway로만 호출
gateway:
  base-url: http://localhost:8080

auth:
  base-url: http://localhost:8083
