app:
  api:
    prefix: /gateway

spring:
  data:
    redis:
      host: s4.java21.net
      port: 6379
      password: ${REDIS_PASSWORD}
      database: 331

# front는 eureka 미사용, gateway로만 호출
gateway:
  base-url: http://localhost:10352

auth:
  base-url: http://localhost:10354