spring:
  application:
    name: front
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  profiles:
    active: dev
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: FULL

# feign 로그 출력용
logging:
  level:
    feign.Logger: DEBUG
    store.bookscamp.front.book.feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG

minio:
  # 브라우저에서 접근 가능한 public base URL (리턴용)
  url: http://storage.java21.net:8000
  access-key: EvJ2FP8gy27lDYolEWGQ
  secret-key: h9uzw85pZPDchOTHzslEOUlNd5cDPFLQnJCofZfH
  bucket:
    book: bookscamp-book-image
    review: bookscamp-review-image

